# This workflow will build a Java project with Gradle
# and then build & push a Docker image to Docker Hub.

name: Java CI with Gradle and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Show Gradle build outputs
        run: ls -R build/libs || echo "No JAR found"

      - name: Rename JAR for Docker
        run: |
          mkdir -p build/libs
          mv build/libs/*.jar build/libs/demo-app-1.0-SNAPSHOT.jar || echo "No JAR to rename"

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: tp109/demo-app
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
